name: Test Node with workflow
on: push
jobs:
  first-job:
    name: Build with Node
    runs-on: ubuntu-latest
    container: node:16.15.1
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node index.js
